spring:
  profiles:
    active:
  devtools:
    restart:
      enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
    jdbc-url: jdbc:clickhouse://47.244.106.14:8123
    username: default
    password: 123456
