@startuml
'开始主行情 -> 开始备行情 : 挂了

activate 开始主行情
开始主行情 -> 写入今天周K

写入今天周K -> 写入今天周K一半

写入今天周K一半 -> 开始备行情 :主行情挂了

开始备行情 -> 删除今天周K : 备行情删除

删除今天周K -> 写入今天周K



写入今天周K一半 -> 删除昨天周K

删除昨天周K -> 删除昨天周K一半

删除昨天周K一半 -> 开始备行情 : 主行情挂了

开始备行情 -> 删除昨天周K: 备行情删除

删除昨天周K一半 -> 写入今天周K

写入今天周K -> 开始主行情


deactivate 开始主行情






@enduml